# Generated by Django 5.1.15 on 2026-03-26 23:15

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegionDailyStatistic",
            fields=[
                (
                    "region_daily_statistic_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("region_id", models.UUIDField()),
                ("region_code_snapshot", models.CharField(max_length=64)),
                ("service_date", models.DateField()),
                ("delivery_count", models.PositiveIntegerField()),
                ("completed_delivery_count", models.PositiveIntegerField()),
                ("exception_delivery_count", models.PositiveIntegerField(default=0)),
                (
                    "total_distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "total_base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "average_delivery_minutes",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("service_date", "region_code_snapshot"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("region_id", "service_date"),
                        name="unique_region_daily_statistic_per_region_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RegionPerformanceSummary",
            fields=[
                (
                    "region_performance_summary_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("region_id", models.UUIDField()),
                ("region_code_snapshot", models.CharField(max_length=64)),
                (
                    "difficulty_level_snapshot",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                        ],
                        max_length=32,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("delivery_count", models.PositiveIntegerField()),
                (
                    "completion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "productivity_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "cost_per_delivery",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("period_start", "region_code_snapshot"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("region_id", "period_start", "period_end"),
                        name="unique_region_performance_summary_per_region_period",
                    )
                ],
            },
        ),
    ]
