# Generated by Django 5.1.15 on 2026-03-21 01:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelemetryRawIngest",
            fields=[
                (
                    "telemetry_raw_ingest_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_terminal_id", models.UUIDField(blank=True, null=True)),
                ("source_vehicle_id", models.UUIDField(blank=True, null=True)),
                ("message_topic", models.CharField(max_length=255)),
                ("message_type", models.CharField(max_length=100)),
                ("payload_json", models.JSONField()),
                ("received_at", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TelemetryTimeseries",
            fields=[
                (
                    "telemetry_timeseries_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_terminal_id", models.UUIDField(blank=True, null=True)),
                ("source_vehicle_id", models.UUIDField(blank=True, null=True)),
                ("captured_at", models.DateTimeField()),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("speed", models.FloatField(blank=True, null=True)),
                ("battery_soc", models.FloatField(blank=True, null=True)),
                ("key_status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "payload_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleLocationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_id", models.UUIDField(unique=True)),
                ("terminal_id", models.UUIDField(unique=True)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("captured_at", models.DateTimeField()),
                (
                    "snapshot_status",
                    models.CharField(
                        choices=[
                            ("fresh", "fresh"),
                            ("stale", "stale"),
                            ("unavailable", "unavailable"),
                        ],
                        default="fresh",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiagnosticEvent",
            fields=[
                (
                    "diagnostic_event_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vehicle_id", models.UUIDField()),
                ("terminal_id", models.UUIDField()),
                ("event_code", models.CharField(max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "info"),
                            ("warning", "warning"),
                            ("critical", "critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_message", models.TextField()),
                ("captured_at", models.DateTimeField()),
                (
                    "event_status",
                    models.CharField(
                        choices=[("open", "open"), ("cleared", "cleared")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vehicle_id", "event_code", "captured_at"),
                        name="unique_vehicle_event_code_captured_at",
                    )
                ],
            },
        ),
    ]
