# Generated by Django 5.1.15 on 2026-03-23 04:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DispatchPlan",
            fields=[
                (
                    "dispatch_plan_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField()),
                ("fleet_id", models.UUIDField()),
                ("dispatch_date", models.DateField()),
                ("planned_volume", models.PositiveIntegerField()),
                (
                    "dispatch_status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("published", "published"),
                            ("closed", "closed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("dispatch_plan_id",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fleet_id", "dispatch_date"),
                        name="unique_dispatch_plan_per_fleet_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VehicleSchedule",
            fields=[
                (
                    "vehicle_schedule_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vehicle_id", models.UUIDField()),
                ("fleet_id", models.UUIDField()),
                ("dispatch_date", models.DateField()),
                ("shift_slot", models.CharField(max_length=32)),
                (
                    "schedule_status",
                    models.CharField(
                        choices=[
                            ("planned", "planned"),
                            ("blocked", "blocked"),
                            ("closed", "closed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("starts_at", models.TimeField(blank=True, null=True)),
                ("ends_at", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("vehicle_schedule_id",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vehicle_id", "dispatch_date", "shift_slot"),
                        name="unique_vehicle_schedule_per_vehicle_date_shift_slot",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DispatchAssignment",
            fields=[
                (
                    "dispatch_assignment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vehicle_id", models.UUIDField()),
                ("driver_id", models.UUIDField()),
                ("operator_company_id", models.UUIDField()),
                ("dispatch_date", models.DateField()),
                ("shift_slot", models.CharField(max_length=32)),
                (
                    "assignment_status",
                    models.CharField(
                        choices=[
                            ("assigned", "assigned"),
                            ("unassigned", "unassigned"),
                        ],
                        max_length=32,
                    ),
                ),
                ("assigned_at", models.DateTimeField()),
                ("unassigned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle_schedule",
                    models.ForeignKey(
                        db_column="vehicle_schedule_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_assignments",
                        to="dispatch.vehicleschedule",
                    ),
                ),
            ],
            options={
                "ordering": ("dispatch_assignment_id",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("assignment_status", "assigned")),
                        fields=("vehicle_schedule",),
                        name="unique_assigned_dispatch_per_vehicle_schedule",
                    )
                ],
            },
        ),
    ]
