# Generated by Django 5.1.15 on 2026-04-05 02:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatchassignment",
            name="driver_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="OutsourcedDriver",
            fields=[
                (
                    "outsourced_driver_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("contact_number", models.CharField(max_length=32)),
                ("vehicle_note", models.CharField(blank=True, default="", max_length=255)),
                ("memo", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dispatch_plan",
                    models.ForeignKey(
                        db_column="dispatch_plan_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outsourced_drivers",
                        to="dispatch.dispatchplan",
                    ),
                ),
            ],
            options={
                "ordering": ("outsourced_driver_id",),
            },
        ),
        migrations.AddField(
            model_name="dispatchassignment",
            name="outsourced_driver",
            field=models.ForeignKey(
                blank=True,
                db_column="outsourced_driver_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispatch_assignments",
                to="dispatch.outsourceddriver",
            ),
        ),
    ]
