# Generated by Django 5.1.15 on 2026-04-09 22:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch", "0004_outsourceddriver_archive_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchUploadBatch",
            fields=[
                ("upload_batch_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_filename", models.CharField(blank=True, default="", max_length=255)),
                ("upload_status", models.CharField(choices=[("draft", "draft"), ("confirmed", "confirmed")], default="draft", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dispatch_plan", models.ForeignKey(db_column="dispatch_plan_id", on_delete=django.db.models.deletion.CASCADE, related_name="upload_batches", to="dispatch.dispatchplan")),
            ],
            options={"ordering": ("upload_batch_id",)},
        ),
        migrations.CreateModel(
            name="DispatchUploadRow",
            fields=[
                ("upload_row_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("row_index", models.PositiveIntegerField(default=0)),
                ("external_user_name", models.CharField(max_length=120)),
                ("small_region_text", models.CharField(blank=True, default="", max_length=255)),
                ("detailed_region_text", models.CharField(blank=True, default="", max_length=255)),
                ("box_count", models.PositiveIntegerField(default=0)),
                ("household_count", models.PositiveIntegerField(default=0)),
                ("matched_driver_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("upload_batch", models.ForeignKey(db_column="upload_batch_id", on_delete=django.db.models.deletion.CASCADE, related_name="rows", to="dispatch.dispatchuploadbatch")),
            ],
            options={"ordering": ("upload_batch_id", "row_index", "upload_row_id")},
        ),
    ]
