# Generated by Django 5.1.15 on 2026-04-10 03:05

import django.db.models.deletion
from django.db import migrations, models


def copy_scope_from_dispatch_plan(apps, schema_editor):
    DispatchUploadBatch = apps.get_model("dispatch", "DispatchUploadBatch")

    for batch in DispatchUploadBatch.objects.select_related("dispatch_plan").all():
        if batch.dispatch_plan_id is None:
            continue
        batch.company_id = batch.dispatch_plan.company_id
        batch.fleet_id = batch.dispatch_plan.fleet_id
        batch.dispatch_date = batch.dispatch_plan.dispatch_date
        batch.save(update_fields=["company_id", "fleet_id", "dispatch_date"])


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch", "0005_dispatchuploadbatch_dispatchuploadrow"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchuploadbatch",
            name="company_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispatchuploadbatch",
            name="dispatch_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispatchuploadbatch",
            name="fleet_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dispatchuploadbatch",
            name="dispatch_plan",
            field=models.ForeignKey(
                blank=True,
                db_column="dispatch_plan_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="upload_batches",
                to="dispatch.dispatchplan",
            ),
        ),
        migrations.RunPython(copy_scope_from_dispatch_plan, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="dispatchuploadbatch",
            name="company_id",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="dispatchuploadbatch",
            name="dispatch_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="dispatchuploadbatch",
            name="fleet_id",
            field=models.UUIDField(),
        ),
    ]
