# Generated by Django 5.1.15 on 2026-04-04 11:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_account_route_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverAccount",
            fields=[
                (
                    "driver_account_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Identity",
            fields=[
                (
                    "identity_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("birth_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("name", "identity_id"),
            },
        ),
        migrations.AlterField(
            model_name="account",
            name="route_no",
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="DriverAccountLink",
            fields=[
                (
                    "driver_account_link_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("driver_id", models.UUIDField()),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                ("unlinked_at", models.DateTimeField(blank=True, null=True)),
                ("unlink_reason", models.CharField(blank=True, max_length=64)),
                (
                    "driver_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_links",
                        to="accounts.driveraccount",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="driveraccount",
            name="identity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_accounts",
                to="accounts.identity",
            ),
        ),
        migrations.CreateModel(
            name="IdentityAccountLink",
            fields=[
                (
                    "identity_account_link_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("system_admin", "System Admin"),
                            ("manager", "Manager"),
                            ("driver", "Driver"),
                        ],
                        max_length=16,
                    ),
                ),
                ("account_id", models.UUIDField()),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                ("unlinked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_links",
                        to="accounts.identity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdentityConsentCurrent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("privacy_policy_version", models.CharField(max_length=32)),
                ("privacy_policy_consented_at", models.DateTimeField()),
                ("location_policy_version", models.CharField(max_length=32)),
                ("location_policy_consented_at", models.DateTimeField()),
                (
                    "identity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_current",
                        to="accounts.identity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdentityConsentHistory",
            fields=[
                (
                    "identity_consent_history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("privacy_policy", "Privacy Policy"),
                            ("location_policy", "Location Policy"),
                        ],
                        max_length=32,
                    ),
                ),
                ("version", models.CharField(max_length=32)),
                ("is_consented", models.BooleanField(default=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_history",
                        to="accounts.identity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdentityLoginMethod",
            fields=[
                (
                    "identity_login_method_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("social", "Social"),
                        ],
                        max_length=16,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_methods",
                        to="accounts.identity",
                    ),
                ),
            ],
            options={
                "ordering": ("identity_id", "method_type", "identity_login_method_id"),
            },
        ),
        migrations.CreateModel(
            name="EmailCredential",
            fields=[
                (
                    "email_credential_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "identity_login_method",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_credential",
                        to="accounts.identityloginmethod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdentityProfileHistory",
            fields=[
                (
                    "identity_profile_history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("birth_date", models.DateField()),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_history",
                        to="accounts.identity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManagerAccount",
            fields=[
                (
                    "manager_account_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField()),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("company_super_admin", "Company Super Admin"),
                            ("vehicle_manager", "Vehicle Manager"),
                            ("settlement_manager", "Settlement Manager"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_accounts",
                        to="accounts.identity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PasswordCredential",
            fields=[
                (
                    "password_credential_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("password_hash", models.CharField(max_length=128)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_credential",
                        to="accounts.identity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhoneCredential",
            fields=[
                (
                    "phone_credential_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone_number", models.CharField(max_length=32, unique=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "identity_login_method",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_credential",
                        to="accounts.identityloginmethod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialCredential",
            fields=[
                (
                    "social_credential_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("kakao", "Kakao"),
                            ("apple", "Apple"),
                            ("google", "Google"),
                        ],
                        max_length=16,
                    ),
                ),
                ("provider_subject", models.CharField(max_length=255)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "identity_login_method",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_credential",
                        to="accounts.identityloginmethod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemAdminAccount",
            fields=[
                (
                    "system_admin_account_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_admin_accounts",
                        to="accounts.identity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdentitySignupRequest",
            fields=[
                (
                    "identity_signup_request_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField()),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("manager_account_create", "Manager Account Create"),
                            ("driver_account_create", "Driver Account Create"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("awaiting_setup", "Awaiting Setup"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_re_request", models.BooleanField(default=False)),
                ("from_company_id", models.UUIDField(blank=True, null=True)),
                ("reject_reason", models.CharField(blank=True, max_length=64)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signup_requests",
                        to="accounts.identity",
                    ),
                ),
                (
                    "reviewed_by_manager_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_signup_requests",
                        to="accounts.manageraccount",
                    ),
                ),
                (
                    "reviewed_by_system_admin_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_signup_requests",
                        to="accounts.systemadminaccount",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="driveraccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("identity",),
                name="uniq_active_driver_account_per_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="manageraccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("identity",),
                name="uniq_active_manager_account_per_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="socialcredential",
            constraint=models.UniqueConstraint(
                fields=("provider_type", "provider_subject"),
                name="uniq_social_provider_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="systemadminaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("identity",),
                name="uniq_active_system_admin_per_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="identitysignuprequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("identity", "company_id", "request_type"),
                name="uniq_pending_signup_request_per_scope",
            ),
        ),
    ]
