# Generated by Django 5.1.15 on 2026-04-04 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_identityconsentcurrent_location_policy_consented_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="identity",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_account",
                to="accounts.identity",
            ),
        ),
    ]
