# Generated by Django 5.1.15 on 2026-04-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_account_identity"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Account",
        ),
    ]
