# Generated by Django 5.1.15 on 2026-04-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_delete_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manageraccount",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("company_super_admin", "Company Super Admin"),
                    ("vehicle_manager", "Vehicle Manager"),
                    ("settlement_manager", "Settlement Manager"),
                    ("fleet_manager", "Fleet Manager"),
                ],
                max_length=32,
            ),
        ),
    ]
