# Generated by Django 5.1.15 on 2026-04-13 01:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_manageraccount_role_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="companymanagerrole",
            name="scope_level",
            field=models.CharField(
                choices=[("company", "Company"), ("fleet", "Fleet")],
                default="company",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ManagerAccountFleetAssignment",
            fields=[
                (
                    "manager_account_fleet_assignment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField()),
                ("fleet_id", models.UUIDField()),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manager_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fleet_assignments",
                        to="accounts.manageraccount",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("manager_account", "fleet_id"),
                        name="uniq_manager_account_fleet_assignment",
                    )
                ],
            },
        ),
    ]
