# Generated by Django 5.1.15 on 2026-04-13 04:26

from django.db import migrations, models


DEFAULT_ROLE_ORDER = {
    "company_super_admin": 1,
    "vehicle_manager": 2,
    "settlement_manager": 3,
    "fleet_manager": 4,
}


def populate_company_manager_role_display_order(apps, schema_editor):
    CompanyManagerRole = apps.get_model("accounts", "CompanyManagerRole")

    company_ids = (
        CompanyManagerRole.objects.filter(is_active=True)
        .values_list("company_id", flat=True)
        .distinct()
    )
    for company_id in company_ids:
        roles = list(
            CompanyManagerRole.objects.filter(company_id=company_id, is_active=True).order_by(
                "created_at",
                "company_manager_role_id",
            )
        )
        next_custom_order = max(DEFAULT_ROLE_ORDER.values(), default=0) + 1
        for role in roles:
            display_order = DEFAULT_ROLE_ORDER.get(role.code)
            if display_order is None:
                display_order = next_custom_order
                next_custom_order += 1
            role.display_order = display_order
            role.save(update_fields=["display_order"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_companymanagerrole_scope_level_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companymanagerrole",
            options={"ordering": ("company_id", "display_order", "created_at")},
        ),
        migrations.AddField(
            model_name="companymanagerrole",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(populate_company_manager_role_display_order, migrations.RunPython.noop),
    ]
