# Generated by Django 5.1.15 on 2026-04-21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SettlementInquiryThread",
            fields=[
                ("thread_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("driver_id", models.UUIDField(unique=True)),
                ("driver_account_id", models.UUIDField(db_index=True)),
                ("status", models.CharField(choices=[("open", "Open"), ("answered", "Answered"), ("closed", "Closed")], default="open", max_length=16)),
                ("latest_message_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("-latest_message_at",)},
        ),
        migrations.CreateModel(
            name="SettlementInquiryMessage",
            fields=[
                ("message_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("author_scope", models.CharField(choices=[("driver", "Driver"), ("operator", "Operator")], max_length=16)),
                ("author_account_id", models.UUIDField()),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "thread",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="settlementinquiry.settlementinquirythread"),
                ),
            ],
            options={"ordering": ("created_at",)},
        ),
        migrations.CreateModel(
            name="SettlementInquiryAttachmentReference",
            fields=[
                ("attachment_reference_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("daily_delivery_input_snapshot_id", models.UUIDField()),
                ("service_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachment_references", to="settlementinquiry.settlementinquirymessage"),
                ),
            ],
            options={"ordering": ("created_at",)},
        ),
    ]
