from django.urls import path

from accounts.views import (
    CompanyManagerRoleDetailView,
    CompanyManagerRoleListCreateView,
    DriverAccountLinkListView,
    DriverAccountLinkUnlinkView,
    DriverAccountManagementListView,
    HealthView,
    IdentityConsentRecoverView,
    IdentityConsentView,
    IdentityConsentWithdrawView,
    IdentityLoginView,
    IdentityLoginMethodDeleteView,
    IdentityLoginMethodListCreateView,
    IdentityLogoutView,
    IdentityMeView,
    IdentityNavigationPolicyView,
    IdentityPasswordView,
    IdentityProfileView,
    IdentityRecoveryView,
    IdentityRefreshView,
    IdentitySignupRequestApproveView,
    IdentitySignupRequestCancelView,
    IdentitySignupRequestCompleteSetupView,
    IdentitySignupRequestIntakeView,
    IdentitySignupRequestManagementListView,
    IdentitySignupRequestRejectView,
    IdentitySignupRequestSelfListView,
    ManagerAccountArchiveView,
    ManagerAccountChangeRoleView,
    ManagerAccountManagementListView,
)

urlpatterns = [
    path("identity-signup-requests/", IdentitySignupRequestIntakeView.as_view(), name="identity-signup-request-intake"),
    path("identity-signup-requests/me/", IdentitySignupRequestSelfListView.as_view(), name="identity-signup-request-self-list"),
    path("identity-signup-requests/manage/", IdentitySignupRequestManagementListView.as_view(), name="identity-signup-request-management-list"),
    path("identity-signup-requests/<uuid:request_id>/cancel/", IdentitySignupRequestCancelView.as_view(), name="identity-signup-request-cancel"),
    path("identity-signup-requests/<uuid:request_id>/approve/", IdentitySignupRequestApproveView.as_view(), name="identity-signup-request-approve"),
    path("identity-signup-requests/<uuid:request_id>/reject/", IdentitySignupRequestRejectView.as_view(), name="identity-signup-request-reject"),
    path("identity-signup-requests/<uuid:request_id>/complete-setup/", IdentitySignupRequestCompleteSetupView.as_view(), name="identity-signup-request-complete-setup"),
    path("identity-login/", IdentityLoginView.as_view(), name="identity-login"),
    path("identity-refresh/", IdentityRefreshView.as_view(), name="identity-refresh"),
    path("identity-logout/", IdentityLogoutView.as_view(), name="identity-logout"),
    path("identity-me/", IdentityMeView.as_view(), name="identity-me"),
    path("identity-navigation-policy/", IdentityNavigationPolicyView.as_view(), name="identity-navigation-policy"),
    path("identity-profile/", IdentityProfileView.as_view(), name="identity-profile"),
    path("identity-consent/", IdentityConsentView.as_view(), name="identity-consent"),
    path("identity-consent/withdraw/", IdentityConsentWithdrawView.as_view(), name="identity-consent-withdraw"),
    path("identity-consent/recover/", IdentityConsentRecoverView.as_view(), name="identity-consent-recover"),
    path("identity-login-methods/", IdentityLoginMethodListCreateView.as_view(), name="identity-login-method-list-create"),
    path("identity-login-methods/<uuid:method_id>/delete/", IdentityLoginMethodDeleteView.as_view(), name="identity-login-method-delete"),
    path("identity-password/", IdentityPasswordView.as_view(), name="identity-password"),
    path("identity-recovery/", IdentityRecoveryView.as_view(), name="identity-recovery"),
    path("manager-accounts/manage/", ManagerAccountManagementListView.as_view(), name="manager-account-management-list"),
    path("manager-accounts/<uuid:manager_account_id>/change-role/", ManagerAccountChangeRoleView.as_view(), name="manager-account-change-role"),
    path("manager-accounts/<uuid:manager_account_id>/archive/", ManagerAccountArchiveView.as_view(), name="manager-account-archive"),
    path("company-manager-roles/", CompanyManagerRoleListCreateView.as_view(), name="company-manager-role-list-create"),
    path("company-manager-roles/<uuid:role_id>/", CompanyManagerRoleDetailView.as_view(), name="company-manager-role-detail"),
    path("driver-accounts/manage/", DriverAccountManagementListView.as_view(), name="driver-account-management-list"),
    path("driver-account-links/", DriverAccountLinkListView.as_view(), name="driver-account-link-list"),
    path("driver-account-links/<uuid:link_id>/unlink/", DriverAccountLinkUnlinkView.as_view(), name="driver-account-link-unlink"),
    path("health/", HealthView.as_view(), name="health"),
]
