from django.urls import path

from accounts.views import (
    AccountDetailView,
    AccountDriverLinkView,
    AccountListCreateView,
    ChangePasswordView,
    HealthView,
    IdentityLoginView,
    IdentityLogoutView,
    IdentityMeView,
    IdentityProfileView,
    IdentityRefreshView,
    IdentitySignupRequestApproveView,
    IdentitySignupRequestCancelView,
    IdentitySignupRequestCompleteSetupView,
    IdentitySignupRequestIntakeView,
    IdentitySignupRequestManagementListView,
    IdentitySignupRequestRejectView,
    IdentitySignupRequestSelfListView,
    LoginView,
    LogoutView,
    MeView,
    RefreshView,
    RegisterView,
)

urlpatterns = [
    path("identity-signup-requests/", IdentitySignupRequestIntakeView.as_view(), name="identity-signup-request-intake"),
    path("identity-signup-requests/me/", IdentitySignupRequestSelfListView.as_view(), name="identity-signup-request-self-list"),
    path("identity-signup-requests/manage/", IdentitySignupRequestManagementListView.as_view(), name="identity-signup-request-management-list"),
    path("identity-signup-requests/<uuid:request_id>/cancel/", IdentitySignupRequestCancelView.as_view(), name="identity-signup-request-cancel"),
    path("identity-signup-requests/<uuid:request_id>/approve/", IdentitySignupRequestApproveView.as_view(), name="identity-signup-request-approve"),
    path("identity-signup-requests/<uuid:request_id>/reject/", IdentitySignupRequestRejectView.as_view(), name="identity-signup-request-reject"),
    path("identity-signup-requests/<uuid:request_id>/complete-setup/", IdentitySignupRequestCompleteSetupView.as_view(), name="identity-signup-request-complete-setup"),
    path("identity-login/", IdentityLoginView.as_view(), name="identity-login"),
    path("identity-refresh/", IdentityRefreshView.as_view(), name="identity-refresh"),
    path("identity-logout/", IdentityLogoutView.as_view(), name="identity-logout"),
    path("identity-me/", IdentityMeView.as_view(), name="identity-me"),
    path("identity-profile/", IdentityProfileView.as_view(), name="identity-profile"),
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("refresh/", RefreshView.as_view(), name="refresh"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("me/", MeView.as_view(), name="me"),
    path("change-password/", ChangePasswordView.as_view(), name="change-password"),
    path("account-driver-links/", AccountDriverLinkView.as_view(), name="account-driver-link"),
    path("accounts/", AccountListCreateView.as_view(), name="account-list"),
    path("accounts/<str:account_ref>/", AccountDetailView.as_view(), name="account-detail"),
    path("health/", HealthView.as_view(), name="health"),
]
